linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './frontend/.eslintrc.json'
  eslint:
    # indicate where is the config file for stylelint
    config: './backend/.eslintrc.json'
    
