linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './frontend/.eslintrc.js'
  eslint:
    # indicate where is the config file for stylelint
    config: './backend/.eslintrc.js'